// ─── Export Results ───────────────────────────────────────────
// PAID_GATE: PDF export (ungated for now — all users get this)

function buildExportText() {
  const date = new Date().toISOString().split('T')[0];
  const lines = [];
  lines.push('BLIND LISTEN — Session Results');
  lines.push(`Date: ${date}`);
  lines.push('');
  lines.push('─── Mix Assignments ───');
  for (let i = 0; i < shuffleMap.length; i++) {
    const fileIdx = shuffleMap[i];
    const name = files[fileIdx].name;
    const lufs = mixLUFS[fileIdx];
    const peak = mixPeak[fileIdx];
    const rms = mixRMS[fileIdx];
    const lufsStr = (lufs !== null && isFinite(lufs)) ? lufs.toFixed(1) + ' LUFS' : '--';
    const peakStr = (peak !== null && isFinite(peak)) ? peak.toFixed(1) + ' dBFS' : '--';
    const rmsStr = (rms !== null && isFinite(rms)) ? rms.toFixed(1) + ' dB RMS' : '--';
    lines.push(`${LABELS[i]}: ${name}`);
    lines.push(`   ${lufsStr} | ${peakStr} peak | ${rmsStr}`);
  }

  // Notes
  const noteInputs = document.querySelectorAll('.note-input');
  const hasNotes = [...noteInputs].some(inp => inp.value.trim());
  if (hasNotes) {
    lines.push('');
    lines.push('─── Notes ───');
    noteInputs.forEach((inp, i) => {
      if (inp.value.trim()) {
        lines.push(`${LABELS[i]}: ${inp.value.trim()}`);
      }
    });
  }

  // Level matching info
  if (levelMatchEnabled) {
    lines.push('');
    lines.push('Level matching: ON');
  }

  // Consistency result
  if (firstPickFileIndex >= 0 && activeIndex >= 0) {
    const currentFileIndex = shuffleMap[activeIndex];
    const same = currentFileIndex === firstPickFileIndex;
    lines.push('');
    lines.push('─── Consistency Check ───');
    lines.push(same
      ? 'CONSISTENT — same file picked both rounds'
      : 'DIFFERENT — different files picked across rounds');
  }

  // Reference track
  if (refFile) {
    lines.push('');
    lines.push(`Reference track: ${refFile.name}`);
  }

  lines.push('');
  lines.push('Generated by Blind Listen — blindlisten.vercel.app');
  return lines.join('\n');
}

function showExportButtons() {
  exportActions.style.display = 'flex';
}

// Copy to clipboard
exportCopyBtn.addEventListener('click', () => {
  const text = buildExportText();
  navigator.clipboard.writeText(text).then(() => {
    const orig = exportCopyBtn.textContent;
    exportCopyBtn.textContent = 'Copied!';
    setTimeout(() => { exportCopyBtn.textContent = orig; }, 1500);
  });
});

// Download .txt
exportTxtBtn.addEventListener('click', () => {
  const text = buildExportText();
  const date = new Date().toISOString().split('T')[0];
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `blind-listen-results-${date}.txt`;
  a.click();
  URL.revokeObjectURL(url);
});

// Download PDF
exportPdfBtn.addEventListener('click', () => {
  if (typeof window.jspdf === 'undefined') {
    console.warn('jsPDF not loaded');
    return;
  }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  const date = new Date().toISOString().split('T')[0];

  let y = 20;
  const lineH = 7;
  const margin = 20;
  const pageW = doc.internal.pageSize.getWidth() - margin * 2;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('Blind Listen — Session Results', margin, y);
  y += lineH * 1.5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Date: ${date}`, margin, y);
  y += lineH * 2;

  // Mix assignments
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Mix Assignments', margin, y);
  y += lineH;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  for (let i = 0; i < shuffleMap.length; i++) {
    const fileIdx = shuffleMap[i];
    const name = files[fileIdx].name;
    const lufs = mixLUFS[fileIdx];
    const peak = mixPeak[fileIdx];
    const lufsStr = (lufs !== null && isFinite(lufs)) ? lufs.toFixed(1) + ' LUFS' : '--';
    const peakStr = (peak !== null && isFinite(peak)) ? peak.toFixed(1) + ' dBFS' : '--';

    doc.setFont('helvetica', 'bold');
    doc.text(`${LABELS[i]}:`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(name, margin + 12, y);
    y += lineH * 0.8;
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`${lufsStr}  |  ${peakStr} peak`, margin + 12, y);
    doc.setTextColor(0);
    doc.setFontSize(10);
    y += lineH;
  }

  // Notes
  const noteInputs = document.querySelectorAll('.note-input');
  const hasNotes = [...noteInputs].some(inp => inp.value.trim());
  if (hasNotes) {
    y += lineH * 0.5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Notes', margin, y);
    y += lineH;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    noteInputs.forEach((inp, i) => {
      if (inp.value.trim()) {
        doc.text(`${LABELS[i]}: ${inp.value.trim()}`, margin, y);
        y += lineH;
      }
    });
  }

  // Consistency
  if (firstPickFileIndex >= 0 && activeIndex >= 0) {
    y += lineH * 0.5;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('Consistency Check', margin, y);
    y += lineH;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const currentFileIndex = shuffleMap[activeIndex];
    const same = currentFileIndex === firstPickFileIndex;
    doc.text(same ? 'CONSISTENT — same file picked both rounds' : 'DIFFERENT — different files picked across rounds', margin, y);
    y += lineH;
  }

  // Footer
  y += lineH;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Blind Listen — blindlisten.vercel.app', margin, y);

  doc.save(`blind-listen-results-${date}.pdf`);
});
